### ISSUE TITLE
Feature: Direct fetch from the rooster website

### ISSUE THREAD

**Issue by retrography** [gandreadis/vu-timetable#2]
The program uses x-www-form-urlencoded form fields over POST requests to fetch the timetables from the website. We must be able to use the course codes to directly fetch the html. I tried on my own but ran into trouble with all the ASPX session information saved in hidden form fields. Yet, this is definitely a possibility because [some others have been able to successfully scrape the whole rooster site](https://vurooster.nl/).

**Comment by retrography** [comment]
I received a response from Anne Jon (the developer of the website above):

> From the top of my mind, you need to do the following witchcraft in order to talk to the server:
> 
> The trick is that you have to replay the __VIEWSTATE and a bunch of other __ prefixed form inputs, which you where given in the previous response in your next request to the server.
> You can't go straight to a "schedule page". You always have to first go to the homepage, navigate to the desired tab using the form, and use the form collection given as a starting point to do all your successive request. There is no way of cheating this.
> 
> So:
> 
> 1. Fetch the homepage https://rooster.vu.nl/
> 2. Find all the input fields that that start with __ 
>     - for example __EVENTVALIDATION and __VIEWSTATE. I think these to are the most important, but it save to collect all of them.
> 3. If needed, use the form to navigate to one of the other page, like Docent, Vak Group
>     - Check the "Do postback function" on which fields to use.
>     - Important: You need to submit 
> 4. Perform a POST with your desired course code, include all the __ form inputs. This should work. Don't forget things like the weeknumber. Also, weeknumbers have a " " (space) as a suffix. They need to be there.

**Comment by gandreadis** [comment]
Thanks for the suggestion and for getting insights from Anne! Fetching the course directly (without the need for manual HTML downloads) would indeed be even better 😄
I hacked this script together in a couple of hours just for myself in the first place, but this automation is the next logical step to make it more useful. I'll see what I can do, as soon as I have some spare time again. I'll let you know when I have some progress on this.

**Comment by retrography** [comment]
Anne has maintained his website for years, and is finally sunsetting it now (he graduated a long time ago). That's a real loss to the community. Maybe you can even pick up where he left and run the site again. But that would be for the general public.  I always prefer the command line version... ;)

**Comment by gandreadis** [comment]
That's sad to hear! I also prefer the command line version though :)
Anyway, with the VU moving to Canvas, and thus with integrated calendar feeds being provided officially, this script will soon become obsolete. But until that transition is completed (and until all courses actually have their timetables added to Canvas, which many haven't yet), we can stick with this hacky workaround ;)

**Comment by retrography** [comment]
Unfortunately I don't think there will be such a thing as integrated calendar feeds anytime soon. There is no software interface connecting the VU enrolment and scheduling system (which is SAP) with that of Canvas. Yesterday I had to sit down and enter the event details for my students and I in Canvas calendar, and I can tell you it is not the most friendly interface. It doesn't even support defining recurrent events or importing calendar files (smart, isn't it?!). I don't expect the other professors to do the same, as it is a lot of hassle, and if any human error goes into it, it is the prof's fault, creating a lot of tension with the students. So, think of this as a permanent hack for your time here... And be thankful of the profs who actually enter the course schedule in Canvas. It is really not an obvious task.

That said, if you have seen that integration appearing somewhere on the deployment roadmap, I will be more than glad to see it happen.

**Comment by gandreadis** [comment]
Oh wow, had no idea it was that much of a hassle! I thought they were going to transition entirely to Canvas, but if it is indeed manual, then you're definitely right - this _will_ probably be a more permanent workaround than I expected. Unfortunate that the VU doesn't deploy something like MyTimeTable (what we use at the TU Delft for distributing schedules to students, and I believe the UvA also uses it).

**Comment by gandreadis** [comment]
Good news: Got something working with Selenium webdriver 🎉
See branch `fetch-site`. This does need [chromedriver](https://sites.google.com/a/chromium.org/chromedriver/) to be installed and on `PATH`, I'll look into ways of maybe packaging a headless webdriver with the script (so that people don't have to download some web driver before being able to run this).

**Comment by retrography** [comment]
Cool! I can't test it tonight, but had a look at the code right now. I see what you are doing. The way I think of it (and Anne said it is possible), is to do all these using http requests without resorting to the browser. It takes 3 consecutive submissions and reparsings to attain the right hidden form field values to submit along with the course code so that you get the timetable. If you snoop the http headers and form values with google chrome's developer view you see what is going on. It is not very complex, just bit stupid. Microsoft/ASP stupid, if you know what I mean! Maybe I try it again one of these days, if I get the time to do so... But for now, you have a simple and working solution.

**Comment by gandreadis** [comment]
Update: I've ported the code to Java, and it now uses a headless Selenium driver to do the browser interaction (so pure command-line, no browser windows popping up). The Gradle build system fetches in all needed dependencies, but I can also now more easily export this into a jar and attach it to a Git release, making it easier for people to use it :)

**Comment by gandreadis** [comment]
Okay, so I've merged the implementation of this feature into master, thereby closing this issue. Do let me know if you encounter any issues/bugs while using the new version :)

**Comment by retrography** [comment]
I made my own toything. Have a look: https://retrography.github.io/VUTt/

**Comment by gandreadis** [comment]
Nice! I've bookmarked it :)  I'll link to it from the README, as being a tool for people who want more fine-grained export controls or simply an alternative way of fetching their timetable.
